In [1]:
### This chunk of notebook will show us the best practice of
### setting the shape of a numpy array/vector in a matrix form operation

In [1]:
import numpy as np

In [27]:
############# This Chunk of Code Is So Important for RESHAPING ############ 
a = np.random.randn(5)
print(a) 
print(a.shape) ### This is just an One Dimensional List of Gaussian numbers
### If u accidentally end up with this Rank 1 Array or in other words an one
### dimensional list like array, u can easily "reshape" it to a 2-D Array of
### your desired shape
print()
print('Reshaping Rank 1 Array to 2-D Array')
a = a.reshape(5, 1)
print(a)
print(a.shape)
print()
a = a.reshape(1, 5)
print(a)
print(a.shape)
###########################################################################

[-1.39353141 -0.56426339  0.50141408  0.36949858  0.00891626]
(5,)

Reshaping Rank 1 Array to 2-D Array
[[-1.39353141]
 [-0.56426339]
 [ 0.50141408]
 [ 0.36949858]
 [ 0.00891626]]
(5, 1)

[[-1.39353141 -0.56426339  0.50141408  0.36949858  0.00891626]]
(1, 5)


In [6]:
print(a.T) ### See nothing happens because it is not an array just a list

[ 0.21735356 -1.19839022  0.40576367 -0.95080303  0.88145153]


In [8]:
print(np.dot(a, a.T)) ### It seems like a scalar multiplication
### What happens here multiplying each element with itself and
### finally adding those all up to find a scalar output

3.329009040263977


In [13]:
### Now the above non dimensionality can be overturned by introducing
### 2 distinct dimensions while creating a random numpy array. The
### following operation outputs a 2-D array
a = np.random.randn(5, 1)
print('2D Array: Row=5, Column=1')
print(a)
print(a.shape)
print()
b = np.random.randn(1, 5)
print('2D Array: Row=1, Column=5')
print(b)
print(b.shape)

2D Array: Row=5, Column=1
[[ 1.17863801]
 [-1.25078264]
 [ 1.17599127]
 [ 1.46876902]
 [-1.72899346]]
(5, 1)

2D Array: Row=1, Column=5
[[-0.22101128  1.94464029  0.14995885  2.07971444  1.27807841]]
(1, 5)


In [17]:
### And now we can apply matrix multiplication to above two
### matrices with expected shape output
### If we do a dot (a transpose) ==> (5, 1) * (1, 5) ==> (5, 5); Final Product Shape
### If we do b dot (b transpose) ==> (1, 5) * (5, 1) ==> (1, 1); Final Product Shape
c = np.dot(a, (a.T))
print(c)
print(c.shape)
print()
d = np.dot(b, (b.T))
print(d)
print(d.shape)
print('Successful, worked as expected!!!')

[[ 1.38918756 -1.47421996  1.38606801  1.73114699 -2.03785741]
 [-1.47421996  1.56445722 -1.47090947 -1.8371108   2.16259501]
 [ 1.38606801 -1.47090947  1.38295547  1.72725955 -2.03328122]
 [ 1.73114699 -1.8371108   1.72725955  2.15728244 -2.53949204]
 [-2.03785741  2.16259501 -2.03328122 -2.53949204  2.9894184 ]]
(5, 5)

[[9.81165609]]
(1, 1)
Successful, worked as expected!!!


In [25]:
### Tiny tips for better execution: when u r unsure about the
### shape of  ur matrix, try the following assertion test
assert(a.shape == (5, 1))
### If the assertion is correct ==> No Error
### If the assertion is wrong ==> Error
#assert(a.shape == (1, 5))

In [2]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [3]:
print(c)

[[ 0.32693643  0.40370213 -0.1256443 ]
 [ 0.1567267  -0.07981756 -0.1295086 ]
 [ 0.18466578 -0.10589211 -0.59211967]]
